SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER ON;

CREATE TABLE [dbo].[Trips]
(
    [id] int IDENTITY(1,1) NOT NULL,
    [TPEPPickupDatetime] datetime NULL,
    [TPEPDropoffDatetime] datetime NULL,
    [PassengerCount] int NULL,
    [TripDistance] float NULL,
    [StoreAndFwdFlag] varchar(50) NULL,
    [PULocationID] int NULL,
    [DOLocationID] int NULL,
    [FareAmount] decimal(10, 2) NULL,
    [TipAmount] decimal(10, 2) NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
    ON [PRIMARY]
    ) ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_DropoffTime] 
ON [dbo].[Trips] ([TPEPDropoffDatetime] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_PickupTime] 
ON [dbo].[Trips] ([TPEPPickupDatetime] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_PULocation] 
ON [dbo].[Trips] ([PULocationID] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_TipAmount] 
ON [dbo].[Trips] ([TipAmount] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY];

CREATE NONCLUSTERED INDEX [IX_TripDistance] 
ON [dbo].[Trips] ([TripDistance] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY];
